import { Restroom, Review } from "./types";

/** mock 화장실 (정적 JSON 로드 실패 시 fallback) */
export const mockRestrooms: Restroom[] = [
  {
    id: "pd-1",
    name: "광화문광장 공중화장실",
    address: "서울 종로구 세종대로 172",
    distance: "120m",
    rating: 4.2,
    review_count: 47,
    tags: ["무료", "장애인 접근 가능", "기저귀 교환대", "24시간"],
    is_open: true,
    source: "public_data",
    status: "approved",
    has_disabled_access: true,
    has_diaper_table: true,
    has_bidet: false,
    is_free: true,
    open_hours: "24시간",
    lat: 37.5719,
    lng: 126.9768,
    created_at: "",
  },
  {
    id: "pd-8",
    name: "강남역 공중화장실",
    address: "서울 강남구 강남대로 지하 396",
    distance: "200m",
    rating: 3.8,
    review_count: 125,
    tags: ["무료", "장애인 접근 가능"],
    is_open: true,
    source: "public_data",
    status: "approved",
    has_disabled_access: true,
    has_diaper_table: false,
    has_bidet: false,
    is_free: true,
    open_hours: "05:30-24:00",
    lat: 37.4980,
    lng: 127.0276,
    created_at: "",
  },
  {
    id: "pd-7",
    name: "잠실역 공중화장실",
    address: "서울 송파구 올림픽로 지하 240",
    distance: "350m",
    rating: 4.5,
    review_count: 89,
    tags: ["무료", "장애인 접근 가능"],
    is_open: true,
    source: "public_data",
    status: "approved",
    has_disabled_access: true,
    has_diaper_table: false,
    has_bidet: false,
    is_free: true,
    open_hours: "05:30-24:00",
    lat: 37.5133,
    lng: 127.1001,
    created_at: "",
  },
  {
    id: "pd-9",
    name: "홍대입구역 공중화장실",
    address: "서울 마포구 양화로 160",
    distance: "450m",
    rating: 2.9,
    review_count: 203,
    tags: ["무료", "장애인 접근 가능"],
    is_open: true,
    source: "public_data",
    status: "approved",
    has_disabled_access: true,
    has_diaper_table: false,
    has_bidet: false,
    is_free: true,
    open_hours: "05:30-24:00",
    lat: 37.5573,
    lng: 126.9255,
    created_at: "",
  },
  {
    id: "pd-6",
    name: "동대문 DDP 공중화장실",
    address: "서울 중구 을지로 281",
    distance: "580m",
    rating: 4.7,
    review_count: 312,
    tags: ["무료", "장애인 접근 가능", "기저귀 교환대"],
    is_open: true,
    source: "public_data",
    status: "approved",
    has_disabled_access: true,
    has_diaper_table: true,
    has_bidet: false,
    is_free: true,
    open_hours: "10:00-22:00",
    lat: 37.5671,
    lng: 127.0095,
    created_at: "",
  },
  {
    id: "pd-12",
    name: "이태원역 공중화장실",
    address: "서울 용산구 이태원로 지하 177",
    distance: "720m",
    rating: 3.2,
    review_count: 56,
    tags: ["무료", "장애인 접근 가능"],
    is_open: true,
    source: "public_data",
    status: "approved",
    has_disabled_access: true,
    has_diaper_table: false,
    has_bidet: false,
    is_free: true,
    open_hours: "05:30-24:00",
    lat: 37.5346,
    lng: 126.9946,
    created_at: "",
  },
  {
    id: "pd-10",
    name: "여의도공원 공중화장실",
    address: "서울 영등포구 여의공원로 68",
    distance: "1.2km",
    rating: 4.6,
    review_count: 178,
    tags: ["무료", "장애인 접근 가능", "기저귀 교환대"],
    is_open: true,
    source: "public_data",
    status: "approved",
    has_disabled_access: true,
    has_diaper_table: true,
    has_bidet: false,
    is_free: true,
    open_hours: "06:00-22:00",
    lat: 37.5265,
    lng: 126.9224,
    created_at: "",
  },
];

export const mockReviews: Review[] = [
  { id: "r1", restroom_key: "pd-1", user_id: "u1", user_name: "김민수", rating: 4, comment: "깨끗하고 관리가 잘 되어 있어요.", has_photo: true, created_at: "2026-03-18" },
  { id: "r2", restroom_key: "pd-1", user_id: "u2", user_name: "이지은", rating: 5, comment: "장애인 화장실도 넓고 편리합니다.", has_photo: false, created_at: "2026-03-15" },
  { id: "r3", restroom_key: "pd-1", user_id: "u3", user_name: "박준영", rating: 3, comment: "점심시간에는 좀 붐벼요.", has_photo: true, created_at: "2026-03-10" },
  { id: "r4", restroom_key: "pd-8", user_id: "u4", user_name: "최수아", rating: 4, comment: "지하상가에서 찾기 쉬운 위치에 있어요.", has_photo: false, created_at: "2026-03-17" },
  { id: "r5", restroom_key: "pd-8", user_id: "u5", user_name: "정우진", rating: 3, comment: "사람이 많아서 대기시간이 좀 있어요.", has_photo: true, created_at: "2026-03-12" },
  { id: "r6", restroom_key: "pd-7", user_id: "u6", user_name: "한소희", rating: 5, comment: "역 안에서 접근이 편리해요.", has_photo: true, created_at: "2026-03-16" },
  { id: "r7", restroom_key: "pd-7", user_id: "u7", user_name: "오세준", rating: 4, comment: "전반적으로 깨끗한 상태입니다.", has_photo: false, created_at: "2026-03-11" },
  { id: "r8", restroom_key: "pd-9", user_id: "u8", user_name: "강하늘", rating: 2, comment: "금요일 밤에는 상태가 안 좋아요.", has_photo: true, created_at: "2026-03-14" },
  { id: "r9", restroom_key: "pd-6", user_id: "u9", user_name: "윤서연", rating: 5, comment: "DDP 화장실은 항상 깨끗해요.", has_photo: true, created_at: "2026-03-18" },
  { id: "r10", restroom_key: "pd-6", user_id: "u10", user_name: "임재현", rating: 5, comment: "서울에서 가장 깨끗한 공용화장실 중 하나.", has_photo: false, created_at: "2026-03-13" },
  { id: "r11", restroom_key: "pd-12", user_id: "u11", user_name: "송민지", rating: 3, comment: "위치는 좋은데 관리 상태가 아쉬워요.", has_photo: false, created_at: "2026-03-09" },
  { id: "r12", restroom_key: "pd-10", user_id: "u12", user_name: "배수진", rating: 5, comment: "공원 화장실치고 정말 깨끗합니다.", has_photo: true, created_at: "2026-03-17" },
];
