import { Restroom, Review } from "./types";

export const mockRestrooms: Restroom[] = [
  {
    id: "1",
    name: "센트럴파크 공용화장실",
    address: "서울 중구 을지로 지하 170",
    distance: "120m",
    rating: 4.2,
    reviewCount: 47,
    tags: ["무료", "장애인 접근 가능", "기저귀 교환대"],
    isOpen: true,
    lat: 37.5665,
    lng: 126.978,
  },
  {
    id: "2",
    name: "강남역 지하상가 화장실",
    address: "서울 강남구 강남대로 396",
    distance: "200m",
    rating: 3.8,
    reviewCount: 125,
    tags: ["무료", "24시간"],
    isOpen: true,
    lat: 37.498,
    lng: 127.0276,
  },
  {
    id: "3",
    name: "롯데마트 잠실점 화장실",
    address: "서울 송파구 올림픽로 240",
    distance: "350m",
    rating: 4.5,
    reviewCount: 89,
    tags: ["깨끗함", "기저귀 교환대", "비데"],
    isOpen: true,
    lat: 37.5133,
    lng: 127.1028,
  },
  {
    id: "4",
    name: "홍대입구역 2번 출구 화장실",
    address: "서울 마포구 양화로 160",
    distance: "450m",
    rating: 2.9,
    reviewCount: 203,
    tags: ["무료", "24시간"],
    isOpen: true,
    lat: 37.5573,
    lng: 126.9255,
  },
  {
    id: "5",
    name: "코엑스몰 B1 화장실",
    address: "서울 강남구 영동대로 513",
    distance: "580m",
    rating: 4.7,
    reviewCount: 312,
    tags: ["깨끗함", "장애인 접근 가능", "비데", "기저귀 교환대"],
    isOpen: true,
    lat: 37.512,
    lng: 127.0590,
  },
  {
    id: "6",
    name: "이태원 공영화장실",
    address: "서울 용산구 이태원로 177",
    distance: "720m",
    rating: 3.2,
    reviewCount: 56,
    tags: ["무료"],
    isOpen: false,
    lat: 37.5346,
    lng: 126.9946,
  },
  {
    id: "7",
    name: "여의도 IFC몰 화장실",
    address: "서울 영등포구 국제금융로 10",
    distance: "1.2km",
    rating: 4.6,
    reviewCount: 178,
    tags: ["깨끗함", "비데", "장애인 접근 가능"],
    isOpen: true,
    lat: 37.5251,
    lng: 126.9256,
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    restroomId: "1",
    userName: "김민수",
    rating: 4,
    comment: "깨끗하고 관리가 잘 되어 있어요. 휴지도 항상 채워져 있습니다.",
    hasPhoto: true,
    createdAt: "2026-03-18",
  },
  {
    id: "r2",
    restroomId: "1",
    userName: "이지은",
    rating: 5,
    comment: "장애인 화장실도 넓고 편리합니다. 기저귀 교환대도 있어서 아기 데리고 가기 좋아요.",
    hasPhoto: false,
    createdAt: "2026-03-15",
  },
  {
    id: "r3",
    restroomId: "1",
    userName: "박준영",
    rating: 3,
    comment: "점심시간에는 좀 붐벼요. 그래도 전반적으로 괜찮은 편.",
    hasPhoto: true,
    createdAt: "2026-03-10",
  },
  {
    id: "r4",
    restroomId: "2",
    userName: "최수아",
    rating: 4,
    comment: "지하상가에서 찾기 쉬운 위치에 있어요. 청소 상태 양호.",
    hasPhoto: false,
    createdAt: "2026-03-17",
  },
  {
    id: "r5",
    restroomId: "2",
    userName: "정우진",
    rating: 3,
    comment: "사람이 많아서 대기시간이 좀 있어요.",
    hasPhoto: true,
    createdAt: "2026-03-12",
  },
  {
    id: "r6",
    restroomId: "3",
    userName: "한소희",
    rating: 5,
    comment: "비데도 있고 정말 깨끗해요! 최고의 화장실입니다.",
    hasPhoto: true,
    createdAt: "2026-03-16",
  },
  {
    id: "r7",
    restroomId: "3",
    userName: "오세준",
    rating: 4,
    comment: "마트 영업시간에만 이용 가능하지만 상태가 좋습니다.",
    hasPhoto: false,
    createdAt: "2026-03-11",
  },
  {
    id: "r8",
    restroomId: "4",
    userName: "강하늘",
    rating: 2,
    comment: "금요일 밤에는 상태가 안 좋아요. 평일 낮에는 괜찮습니다.",
    hasPhoto: true,
    createdAt: "2026-03-14",
  },
  {
    id: "r9",
    restroomId: "5",
    userName: "윤서연",
    rating: 5,
    comment: "코엑스몰 화장실은 항상 기대를 저버리지 않아요. 비데, 핸드드라이어 모두 갖춰져 있습니다.",
    hasPhoto: true,
    createdAt: "2026-03-18",
  },
  {
    id: "r10",
    restroomId: "5",
    userName: "임재현",
    rating: 5,
    comment: "서울에서 가장 깨끗한 공용화장실 중 하나.",
    hasPhoto: false,
    createdAt: "2026-03-13",
  },
  {
    id: "r11",
    restroomId: "6",
    userName: "송민지",
    rating: 3,
    comment: "위치는 좋은데 관리 상태가 아쉬워요.",
    hasPhoto: false,
    createdAt: "2026-03-09",
  },
  {
    id: "r12",
    restroomId: "7",
    userName: "배수진",
    rating: 5,
    comment: "IFC몰답게 화장실도 고급스럽습니다.",
    hasPhoto: true,
    createdAt: "2026-03-17",
  },
];
